services:
  backend:
    build: 
        context: ./Backend354
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build: 
        context: ./frontend354
        dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend354/:/app 
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable file watching
